<?php
include('inc/php/classes/Configuration/information.php');
include('inc/php/classes/Divers/autoload.php');
$oPage = new Page\structure('Récit de Margaw - Nouvelle d\'auteur', 'entete.php', 'footer.php', '
<script src="inc/js/styles.js"></script>
<script src="inc/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script>
	$(document).ready(function(){
		$("article").mCustomScrollbar({
			theme:"minimal-dark",
			axis:"y"
			});
		});
</script>
');
?>
    <section class="nouvelle">
        <nav>
            <li><a href="#chap1">chapitre 1</a></li>
            <li><a href="#chap2">chapitre 2</a></li>
            <li><a href="#chap3">chapitre 3</a></li>
            <li><a href="#chap4">chapitre 4</a></li>
            <li><a href="#chap5">chapitre 5</a></li>
            <li><a href="#chap6">chapitre 6</a></li>
            <li><a href="#chap7">chapitre 7</a></li>
            <li><a href="#chap8">chapitre 8</a></li>
            <li><a href="#chap9">chapitre 9</a></li>
        </nav>
        <article id="chap1">
           <div>Chapitre 1 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
            <br> </article>
        <article id="chap2" class="hide">
            <div>Chapitre 2 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
        </article>
        <article id="chap3" class="hide">
            <div>Chapitre 3 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
        </article>
        <article id="chap4" class="hide">
            <div>Chapitre 4 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
        </article>
        <article id="chap5" class="hide">
            <div>Chapitre 5 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
        </article>
        <article id="chap6" class="hide">
            <div>Chapitre 6 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
        </article>
        <article id="chap7" class="hide">
            <div>Chapitre 7 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
        </article>
        <article id="chap8" class="hide">
            <div>Chapitre 8 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
        </article>
        <article id="chap9" class="hide">
            <div>Chapitre 9 :</div><br>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae ante at tellus pretium convallis. Quisque dapibus, lacus sit amet fermentum laoreet, sapien mauris commodo urna, sed molestie urna tellus a eros. Mauris erat eros, iaculis nec ultrices ut, elementum vitae velit. Aliquam ut magna eget leo dapibus venenatis. Praesent vel condimentum est. Integer sed vestibulum erat, et sagittis sapien. Fusce a augue euismod, laoreet turpis id, dictum tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed vestibulum faucibus magna nec porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In id ligula lectus. Morbi lacus est, posuere ut ante quis, mollis vulputate nulla. Sed maximus magna vitae rhoncus pulvinar. Fusce vitae est cursus, euismod dui at, feugiat quam.</div>
            <br>
            <div>Nulla efficitur sapien vitae est facilisis semper. Aenean eu sodales purus. Nulla vestibulum vestibulum orci, sed mollis velit aliquam eget. Fusce quis vulputate mauris. Praesent ut dui ac tellus sollicitudin dapibus. Donec sit amet venenatis urna. Suspendisse in pharetra mi. Vivamus ante orci, dictum pretium nisl ut, ornare malesuada lorem. Vivamus congue nibh ut nibh gravida, non convallis sapien tempor. Praesent sagittis, felis eu mattis placerat, enim metus mattis neque, nec tincidunt ipsum libero a ipsum. Etiam vestibulum turpis ut diam elementum auctor. Suspendisse posuere erat sem, eu pharetra nisi sollicitudin id. Cras at urna ac orci suscipit fermentum. Cras placerat leo imperdiet dolor sollicitudin, vel mollis arcu consectetur. Aenean id sagittis est, et efficitur leo.</div>
            <br>
            <div>Aliquam volutpat mauris elit, vitae dignissim enim ultrices non. Pellentesque semper posuere nisl, a mollis mi fringilla at. Vivamus lacinia libero massa, vitae scelerisque velit fermentum in. Quisque vel dolor sit amet velit ornare tristique eu sollicitudin augue. Aenean viverra, sapien et mattis tincidunt, dui purus bibendum lacus, venenatis commodo urna magna ut risus. Maecenas congue ante sem, ac ultricies augue facilisis eget. Aliquam imperdiet erat justo, sed vehicula elit aliquet vitae. Morbi commodo ipsum metus, a fringilla nisi interdum nec. Etiam ac faucibus lectus. Sed vel pulvinar risus. Maecenas pulvinar felis mauris, sit amet ultrices velit tristique in. Donec elementum mi at sapien sagittis dapibus. Fusce vitae mi metus. Praesent placerat in justo quis porta. Morbi feugiat facilisis quam vitae laoreet.</div>
            <br>
            <div>Nulla imperdiet libero eu auctor mattis. Cras rhoncus quis mauris vel bibendum. Aliquam quis tempor purus. Sed egestas lacinia ligula, vel accumsan augue elementum a. Duis sed dignissim justo, sed fermentum turpis. Mauris efficitur, tortor a ultricies semper, orci lacus finibus libero, nec gravida eros tellus sed ipsum. Ut sapien sem, venenatis eget tempus convallis, cursus ut lectus. Integer at odio sed libero lacinia ultrices quis pellentesque orci. Fusce eget maximus mauris. Donec viverra orci justo, non condimentum lacus dictum in. Quisque pharetra libero condimentum velit aliquam euismod. Nam ut sagittis odio. Nunc in lectus odio. Phasellus sollicitudin pellentesque tincidunt. Fusce congue neque nulla, vulputate mattis tellus venenatis vel. Duis accumsan lectus mauris, in pulvinar tellus hendrerit ac.</div>
            <br>
            <div>Nulla lacinia pretium turpis sed aliquet. Vestibulum vel lectus eget eros mattis malesuada ut non nibh. Quisque ante erat, interdum nec vehicula a, ornare eu erat. Ut convallis sapien id felis porttitor finibus. Donec id elit id justo rhoncus suscipit vel non erat. Sed ut sagittis purus. Sed vitae pellentesque leo. Curabitur hendrerit malesuada felis, vitae sagittis urna venenatis et. Proin vulputate bibendum massa, nec pretium nulla vestibulum sed. Nullam eu mollis ipsum. Nullam malesuada velit turpis, pellentesque pretium nisi imperdiet eget. Donec et diam neque. </div>
        </article>
    </section>